# Configuration of Hugo
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

timeout = 100000

# Title of your site
title = "FisiQu√≠micamente"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
# baseurl = "https://fisiquimicamente.com/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; 2020&ndash;2021 Rodrigo Alcaraz de la Osa"

############################
## Advanced options below ##
############################

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "es"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
[permalinks]
  authors = "/author/:slug/"
  tags = "/etiqueta/:slug/"
  categories = "/categoria/:slug/"
  publication_types = "/publication-type/:slug/"
  post = "/blog/:year/:month/:day/:slug"

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest", "headers" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]  
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 75
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
  
# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 20.0

  [[related.indices]]
    name = "summary"
    weight = 10.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 40.0
	
# Install Wowchemy
[module]  
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5"
    disable = true
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5"

[minify]
  disableHTML = true

[security]
  _merge = 'deep'