# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the Spanish version of the site.
[es]
  baseURL = "https://fisiquimicamente.com/"
  languageCode = "es"
  contentDir = "content/es"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.  
  
[en]
  baseURL = "https://physichemically.com/"
  languageCode = "en"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title = "PhysiChemically"

  [en.permalinks]
    authors = "/author/:slug/"
    tags = "/tag/:slug/"
    categories = "/category/:slug/"
    publication_types = "/publication-type/:slug/"
    post = "/blog/:year/:month/:day/:slug"
  [en.params]    
    email = "contact@physichemically.com"
	  # address = {region = "Cantabria", country = "Spain", country_code = "ES"}
    contact_links = [
      {icon = "twitter", icon_pack = "fab", name = "Follow us on Twitter", link = "https://twitter.com/fqmente"},
      {icon = "instagram", icon_pack = "fab", name = "Follow us on Instagram", link = "https://www.instagram.com/fisiquimicamente/"},
      {icon = "pinterest", icon_pack = "fab", name = "Follow us on Pinterest", link = "https://www.pinterest.es/fisiquimicamente/"},
      {icon = "discord", icon_pack = "fab", name = "Join the Discord server", link = "https://discord.gg/kJqPqTJ"},
    ]
    [en.params.marketing.seo]
      org_name = "PhysiChemically"
  	  description = "Physics and Chemistry Resources, Tutorials and Current Science"

[ca]
  baseURL = "https://fisiquimicament.com/"
  languageCode = "ca"
  contentDir = "content/ca"
  title = "FisiQuímicament"
  [ca.params]    
    email = "contacte@fisiquimicament.com"
    # address = {region = "Cantabria", country = "Espanya", country_code = "ES"}
    contact_links = [
      {icon = "twitter", icon_pack = "fab", name = "Segueix-nos a Twitter", link = "https://twitter.com/fqmente"},
      {icon = "instagram", icon_pack = "fab", name = "Segueix-nos a Instagram", link = "https://www.instagram.com/fisiquimicamente/"},
      {icon = "pinterest", icon_pack = "fab", name = "Segueix-nos a Pinterest", link = "https://www.pinterest.es/fisiquimicamente/"},
      {icon = "discord", icon_pack = "fab", name = "Uneix-te a el servidor d'Discord", link = "https://discord.gg/kJqPqTJ"},
    ]
    [ca.params.marketing.seo]
      org_name = "FisiQuímicament"
      description = "Recursos de Física i Química, tutorials i ciència d'actualitat"

# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
