# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: âš›ï¸ Recursos FyQ
    url: recursos-fisica-quimica/
    identifier: recursos-fyq
    weight: 1
  - name: ğŸ“š Apuntes
    url: recursos-fisica-quimica/apuntes
    parent: recursos-fyq
    weight: 1
  - name: ğŸ§© Actividades/juegos
    url: recursos-fisica-quimica/actividades-juegos
    parent: recursos-fyq
    weight: 2
  - name: ğŸ“– Historia de la Ciencia
    url: recursos-fisica-quimica/historia-ciencia
    parent: recursos-fyq
    weight: 3
  - name: ğŸ“ EBAU
    url: recursos-fisica-quimica/ebau
    parent: recursos-fyq
    weight: 4
  - name: ğŸ“ Oposiciones
    url: recursos-fisica-quimica/oposiciones
    parent: recursos-fyq
    weight: 5
  - name: â˜¢ï¸ RadiofÃ­sica
    url: recursos-fisica-quimica/radiofisica
    parent: recursos-fyq
    weight: 6
  - name: ğŸ¤ Tutoriales
    url: tutoriales/  
    identifier: tutoriales
    weight: 2
  - name: LaTeX
    parent: tutoriales
    url: tutoriales/latex
    weight: 1
  - name: PresentaciÃ³n de informaciÃ³n
    parent: tutoriales
    url: tutoriales/presentacion-informacion
    weight: 2    
  - name: ğŸ”— Enlaces de interÃ©s
    url: enlaces-interes/  
    identifier: enlaces-interes
    weight: 3
  - name: ğŸ’» Recursos online
    url: enlaces-interes/recursos-online
    parent: enlaces-interes
    weight: 1
  - name: ğŸ¤— PÃ¡ginas amigas
    url: enlaces-interes/paginas-amigas
    parent: enlaces-interes
    weight: 2
  - name: âœï¸ Blog
    url: /blog
    weight: 4
  - name: ğŸ‘¥ Equipo
    url: equipo/
    identifier: equipo
    weight: 5
