# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "âš›ï¸ Recursos FiQ"
  url = "recursos-fisica-quimica/"
  identifier = "recursos-fiq"
  weight = 1
  
[[main]]
  name = "ğŸ“š Apunts"
  url = "recursos-fisica-quimica/apunts"
  parent = "recursos-fiq"
  weight = 1

[[main]]
  name = "ğŸ“ PAU/PBAU"
  url = "recursos-fisica-quimica/pau-pbau"
  parent = "recursos-fiq"
  weight = 2  

[[main]]
  name = "ğŸ‘ Tutorials"
  url = "tutorials/"  
  identifier = "tutorials"
  weight = 2
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutorials"
  url = "tutorials/latex"
  weight = 1
  
[[main]]
  name = "PresentaciÃ³ d'informaciÃ³"
  parent = "tutorials"
  url = "tutorials/presentacio-informacio"
  weight = 2    

[[main]]
  name = "ğŸ”— Recursos online"
  url = "recursos-online/"
  identifier = "recursos-online"
  weight = 4 

# [[main]]
#   name = "ğŸ—ï¸ Novetats"
#   url = "#novetats"
#   identifier = "novetats"
#   weight = 4

# [[main]]
#   name = "Twitter"
#   url = "#novetats"
#   parent = "novetats"
#   weight = 1  
#   pre = "<i class='fab fa-twitter mr-1'></i>"  
  
# [[main]]
#   name = "âœï¸ Blog"
#   url = "/blog"
#   parent = "novetats"
#   weight = 2  

[[main]]
  name = "âœï¸ Blog"
  url = "/blog"
  weight = 5      

[[main]]
  name = "ğŸ‘¥ Equip"
  url = "equip/"
  identifier = "equip"
  weight = 6   

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
