# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "âš›ï¸ Recursos FyQ"
  url = "recursos-fisica-quimica/"
  identifier = "recursos-fyq"
  weight = 1
  
[[main]]
  name = "ğŸ“š Apuntes"
  url = "recursos-fisica-quimica/apuntes"
  parent = "recursos-fyq"
  weight = 1

[[main]]
  name = "ğŸ—’ï¸ Actividades"
  url = "recursos-fisica-quimica/actividades"
  parent = "recursos-fyq"
  weight = 2  

[[main]]
  name = "ğŸ“ EBAU"
  url = "recursos-fisica-quimica/ebau"
  parent = "recursos-fyq"
  weight = 3
  
[[main]]
  name = "ğŸ“ Oposiciones"
  url = "recursos-fisica-quimica/oposiciones"
  parent = "recursos-fyq"
  weight = 4

[[main]]
  name = "ğŸ‘ğŸ¼ Tutoriales"
  url = "tutoriales/"  
  identifier = "tutoriales"
  weight = 2
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "PresentaciÃ³n de informaciÃ³n"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "ğŸ”— Enlaces de interÃ©s"
  url = "enlaces-interes/"  
  identifier = "enlaces-interes"
  weight = 3
  
[[main]]
  name = "ğŸ’» Recursos online"
  url = "enlaces-interes/recursos-online"
  parent = "enlaces-interes"
  weight = 1
  
[[main]]
  name = "ğŸ¤— PÃ¡ginas amigas"
  url = "enlaces-interes/paginas-amigas"
  parent = "enlaces-interes"
  weight = 2

# [[main]]
#   name = "ğŸ—ï¸ Novedades"
#   url = "#novedades"
#   identifier = "novedades"
#   weight = 4

# [[main]]
#   name = "Twitter"
#   url = "#novedades"
#   parent = "novedades"
#   weight = 1  
#   pre = "<i class='fab fa-twitter mr-1'></i>"  
  
# [[main]]
#   name = "âœğŸ¼ Blog"
#   url = "/blog"
#   parent = "novedades"
#   weight = 2

[[main]]
  name = "âœğŸ¼ Blog"
  url = "/blog"
  weight = 4

[[main]]
  name = "ğŸ‘¥ Equipo"
  url = "equipo/"
  identifier = "equipo"
  weight = 5   

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
