# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "游닄 Apuntes"
  url = "apuntes/"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "2췈 ESO"
  url = "apuntes/#segundo-eso"
  parent = "apuntes"
  weight = 1

[[main]]
  name = "3췈 ESO"
  url = "apuntes/#tercero-eso"
  parent = "apuntes"
  weight = 2

[[main]]
  name = "4췈 ESO"
  url = "apuntes/#cuarto-eso"
  parent = "apuntes"
  weight = 3

[[main]]
  name = "1췈 Bach"
  url = "apuntes/#primero-bach"
  parent = "apuntes"
  weight = 4

[[main]]
  name = "2췈 Bach"
  url = "apuntes/#segundo-bach"
  parent = "apuntes"
  weight = 5  
  
[[main]]
  name = "九꽲잺 Recursos EBAU"
  url = "recursos-ebau/"
  identifier = "recursos-ebau"
  weight = 2
  
[[main]]
  name = "Ex치menes"
  url = "recursos-ebau/#examenes-fisica"
  parent = "recursos-ebau"
  weight = 1
  
[[main]]
  name = "Consejos"
  url = "recursos-ebau/#consejos"
  parent = "recursos-ebau"
  weight = 2      

[[main]]
  name = "Tutoriales"
  url = "tutoriales/"  
  identifier = "tutoriales"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "Presentaci칩n de informaci칩n"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "Enlaces de inter칠s"
  url = "enlaces-interes/"  
  identifier = "enlaces-interes"
  weight = 4
  
[[main]]
  name = "Recursos online"
  url = "enlaces-interes/#recursos-online"
  parent = "enlaces-interes"
  weight = 1
  
[[main]]
  name = "P치ginas amigas"
  url = "enlaces-interes/#paginas-amigas"
  parent = "enlaces-interes"
  weight = 2

[[main]]
  name = "Blog"
  url = "post/"
  weight = 5

[[main]]
  name = "Sobre m칤"
  url = "sobre-mi/"
  weight = 6

[[main]]
  name = "Contacto"
  url = "#contacto"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
