# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "ğŸ“š Notes"
  url = "apuntes/"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "2nd grade"
  url = "apuntes/#segundo-eso"
  parent = "apuntes"
  weight = 1

[[main]]
  name = "3rd grade"
  url = "apuntes/#tercero-eso"
  parent = "apuntes"
  weight = 2

[[main]]
  name = "4th grade"
  url = "apuntes/#cuarto-eso"
  parent = "apuntes"
  weight = 3

[[main]]
  name = "1st Bach"
  url = "apuntes/#primero-bach"
  parent = "apuntes"
  weight = 4

[[main]]
  name = "2nd Bach Physics"
  url = "apuntes/#segundo-bach-fisica"
  parent = "apuntes"
  weight = 5
  
[[main]]
  name = "2nd Bach Chemistry"
  url = "apuntes/#segundo-bach-quimica"
  parent = "apuntes"
  weight = 6  
  
[[main]]
  name = "ğŸ“ EBAU resources"
  url = "recursos-ebau/"
  identifier = "recursos-ebau"
  weight = 2
  
[[main]]
  name = "â˜¢ï¸ Physics"
  url = "recursos-ebau/#examenes-fisica"
  parent = "recursos-ebau"
  weight = 1
  
[[main]]
  name = "âš—ï¸ Chemistry"
  url = "recursos-ebau/#examenes-quimica"
  parent = "recursos-ebau"
  weight = 2  
  
[[main]]
  name = "ğŸ’¡ Tips"
  url = "recursos-ebau/#consejos"
  parent = "recursos-ebau"
  weight = 3  

[[main]]
  name = "ğŸ‘ Tutorials"
  url = "tutoriales/"
  identifier = "tutoriales"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "Presentation of information"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "ğŸ”— Links of interest"
  url = "enlaces-interes/"  
  identifier = "enlaces-interes"
  weight = 4
  
[[main]]
  name = "Online resources"
  url = "enlaces-interes/#recursos-online"
  parent = "enlaces-interes"
  weight = 1
  
[[main]]
  name = "Friend pages"
  url = "enlaces-interes/#paginas-amigas"
  parent = "enlaces-interes"
  weight = 2

[[main]]
  name = "ğŸ—ï¸ News"
  url = "#novedades"
  identifier = "novedades"
  weight = 5

[[main]]
  name = "ğŸ¦ Twitter"
  url = "#novedades"
  parent = "novedades"
  weight = 1  
  
[[main]]
  name = "ğŸ’¬ Blog"
  url = "/post"
  parent = "novedades"
  weight = 2    

[[main]]
  name = "ğŸ‘¨â€ğŸ”¬ About me"
  url = "sobre-mi/"
  identifier = "sobre-mi"
  weight = 6
  
[[main]]
  name = "ğŸ‘¨â€ğŸ”¬ Interests and education"
  url = "sobre-mi/"
  parent = "sobre-mi"
  weight = 1

[[main]]
  name = "ğŸ‘£ Career path"
  url = "sobre-mi/#trayectoria-profesional"
  parent = "sobre-mi"
  weight = 2  
  
[[main]]
  name = "âœˆï¸ Research stays"
  url = "sobre-mi/#estancias-investigacion"
  parent = "sobre-mi"
  weight = 3    

[[main]]
  name = "âœ‰ï¸ Contact"
  url = "#contacto"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
