# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "ğŸ“š Notes"
  url = "physics-chemistry-notes/"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "ğŸ“— 13-14 year-olds"
  url = "physics-chemistry-notes/13-14-year-olds"
  parent = "apuntes"
  weight = 1

[[main]]
  name = "ğŸ“˜ 14-15 year-olds"
  url = "physics-chemistry-notes/14-15-year-olds"
  parent = "apuntes"
  weight = 2

[[main]]
  name = "ğŸ“™ 15-16 year-olds"
  url = "physics-chemistry-notes/15-16-year-olds"
  parent = "apuntes"
  weight = 3

[[main]]
  name = "ğŸ“• 16-17 year-olds"
  url = "physics-chemistry-notes/16-17-year-olds"
  parent = "apuntes"
  weight = 4

[[main]]
  name = "ğŸ““ 17-18 year-olds"
  url = "physics-chemistry-notes/17-18-year-olds"
  parent = "apuntes"
  weight = 5 
  
[[main]]
  name = "ğŸ“” Nomenclature of Chemistry"
  url = "physics-chemistry-notes/nomenclature-chemistry"
  parent = "apuntes"
  weight = 6  

[[main]]
  name = "ğŸ¤ Tutorials"
  url = "tutorials/"
  identifier = "tutoriales"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutoriales"
  url = "tutorials/latex"
  weight = 1
  
[[main]]
  name = "Presentation of Information"
  parent = "tutoriales"
  url = "tutorials/presentation-information"
  weight = 2    

[[main]]
  name = "ğŸ”— Online Resources"
  url = "online-resources/"
  identifier = "enlaces-interes"
  weight = 4  

# [[main]]
#   name = "ğŸ—ï¸ News"
#   url = "#news"
#   identifier = "news"
#   weight = 5

# [[main]]
#   name = "Twitter"
#   url = "#news"
#   parent = "news"
#   weight = 1
#   pre = "<i class='fab fa-twitter mr-1'></i>"  
  
# [[main]]
#   name = "âœï¸ Blog"
#   url = "/blog"
#   parent = "news"
#   weight = 2 

[[main]]
  name = "âœï¸ Blog"
  url = "/blog"
  weight = 5 

[[main]]
  name = "ğŸ‘¥ Team"
  url = "team/"
  identifier = "team"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
