# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "ğŸ“š Notes"
  url = "notes/"
  identifier = "notes"
  weight = 1
  
[[main]]
  name = "2nd grade"
  url = "notes/#second-grade"
  parent = "notes"
  weight = 1

[[main]]
  name = "3rd grade"
  url = "notes/#third-grade"
  parent = "notes"
  weight = 2

[[main]]
  name = "4th grade"
  url = "notes/#fourth-grade"
  parent = "notes"
  weight = 3

[[main]]
  name = "1st Bach"
  url = "notes/#first-bach"
  parent = "notes"
  weight = 4

[[main]]
  name = "2nd Bach Physics"
  url = "notes/#second-bach-physics"
  parent = "notes"
  weight = 5
  
[[main]]
  name = "2nd Bach Chemistry"
  url = "notes/#second-bach-chemistry"
  parent = "notes"
  weight = 6  
  
[[main]]
  name = "ğŸ“ EBAU resources"
  url = "ebau-resources/"
  identifier = "ebau-resources"
  weight = 2
  
[[main]]
  name = "â˜¢ï¸ Physics"
  url = "ebau-resources/#physics-exams"
  parent = "ebau-resources"
  weight = 1
  
[[main]]
  name = "âš—ï¸ Chemistry"
  url = "ebau-resources/#chemistry-exams"
  parent = "ebau-resources"
  weight = 2  
  
[[main]]
  name = "ğŸ’¡ Tips"
  url = "ebau-resources/#tips"
  parent = "ebau-resources"
  weight = 3  

[[main]]
  name = "ğŸ‘ Tutorials"
  url = "tutorials/"  
  identifier = "tutorials"
  weight = 3
  
[[main]]
  name = "$\\LaTeX$"
  parent = "tutorials"
  url = "tutorials/latex"
  weight = 1
  
[[main]]
  name = "Presentation of information"
  parent = "tutorials"
  url = "tutorials/presentation-information"
  weight = 2    

[[main]]
  name = "ğŸ”— Links of interest"
  url = "links-interest/"  
  identifier = "links-interest"
  weight = 4
  
[[main]]
  name = "Online resources"
  url = "links-interest/#online-resources"
  parent = "links-interest"
  weight = 1
  
[[main]]
  name = "Friend pages"
  url = "links-interest/#friend-pages"
  parent = "links-interest"
  weight = 2

[[main]]
  name = "ğŸ—ï¸ News"
  url = "#news"
  identifier = "news"
  weight = 5

[[main]]
  name = "ğŸ¦ Twitter"
  url = "#news"
  parent = "news"
  weight = 1  
  
[[main]]
  name = "ğŸ’¬ Blog"
  url = "/post"
  parent = "news"
  weight = 2    

[[main]]
  name = "ğŸ‘¨â€ğŸ”¬ About me"
  url = "about-me/"
  identifier = "about-me"
  weight = 6
  
[[main]]
  name = "ğŸ‘¨â€ğŸ”¬ Interests and education"
  url = "about-me/"
  parent = "about-me"
  weight = 1

[[main]]
  name = "ğŸ‘£ Career path"
  url = "about-me/#career-path"
  parent = "about-me"
  weight = 2  
  
[[main]]
  name = "âœˆï¸ Research stays"
  url = "about-me/#research-stays"
  parent = "about-me"
  weight = 3    

[[main]]
  name = "âœ‰ï¸ Contact"
  url = "#contact"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
