# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Apuntes"
  identifier = "apuntes"
  weight = 1
  
[[main]]
  name = "2º ESO"
  url = "apuntes/#segundo-eso"
  parent = "apuntes"
  weight = 1

[[main]]
  name = "3º ESO"
  url = "apuntes/#tercero-eso"
  parent = "apuntes"
  weight = 2

[[main]]
  name = "4º ESO"
  url = "apuntes/#cuarto-eso"
  parent = "apuntes"
  weight = 3

[[main]]
  name = "1º Bach"
  url = "apuntes/#primero-bach"
  parent = "apuntes"
  weight = 4

[[main]]
  name = "2º Bach"
  url = "apuntes/#segundo-bach"
  parent = "apuntes"
  weight = 5

[[main]]
  name = "Tutoriales"
  identifier = "tutoriales"
  weight = 2
  
[[main]]
  name = "LaTeX"
  parent = "tutoriales"
  url = "tutoriales/latex"
  weight = 1
  
[[main]]
  name = "Presentación de información"
  parent = "tutoriales"
  url = "tutoriales/presentacion-informacion"
  weight = 2    

[[main]]
  name = "Enlaces de interés"
  url = "enlaces/"
  weight = 3

[[main]]
  name = "Blog"
  url = "blog/"
  weight = 4

[[main]]
  name = "Contacto"
  url = "#contacto"
  weight = 5  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
