[build]
  command = '"hugo --gc --minify -b $URL && npx pagefind -y --source "public"'

[build.environment]
  GO_VERSION = "1.18.4"
  HUGO_VERSION = "0.101.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "https://rodrigoalcarazdelaosa.me/*"
  to = "https://fisiquimicamente.com/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/apuntes-2eso-3eso/*"
  to = "/recursos-fisica-quimica/apuntes/2eso-3eso/:splat"
  status = 301  

[[redirects]]
  from = "/apuntes-4eso/*"
  to = "/recursos-fisica-quimica/apuntes/4eso/:splat"
  status = 301

[[redirects]]
  from = "/apuntes-1bach/*"
  to = "/recursos-fisica-quimica/apuntes/1bach/:splat"
  status = 301

[[redirects]]
  from = "/apuntes-2bach-quimica/*"
  to = "/recursos-fisica-quimica/apuntes/2bach/quimica/:splat"
  status = 301        

[[redirects]]
  from = "/apuntes-formulacion-nomenclatura-quimica/inorganica/*"
  to = "/recursos-fisica-quimica/apuntes/formulacion-nomenclatura-quimica/inorganica/:splat"
  status = 301

[[redirects]]
  from = "/apuntes-formulacion-nomenclatura-quimica/organica/*"
  to = "/recursos-fisica-quimica/apuntes/formulacion-nomenclatura-quimica/organica/:splat"
  status = 301

[[redirects]]
  from = "/en/*"
  to = "https://physichemically.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ca/*"
  to = "https://fisiquimicament.com/:splat"
  status = 301
  force = true  

[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  force = true    